version: '3'
volumes:
  pg_data:
  static:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    volumes:
      - static:/backend_static
    env_file: .env
    depends_on:
      - db
  fronted:
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    env_file: .env
  gateway:
    build: ./gateway/
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
